#include <stdint.h>
#include "graphics/bitmapImage.hpp"
#include "graphics/colorLUT.hpp"
//This file is autogenerated and contains asset data to be stored in ROM.
//(c) Daniel Cooper and Artists 2021

const uint16_t bomb_colorLUT_lut[] = { 0, 0, 26365, 42008, 54924, 50562, 50171,
		 43774, 30381, 2236, 8702, 61612, 58819, 10281};

ColorLUT bomb_colorLUT = ColorLUT((uint16_t*)bomb_colorLUT_lut);

const uint8_t bomb_0_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1,
		 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 3, 1, 1, 0, 0, 0, 0, 1, 3, 4, 4, 5, 3, 5,
		 1, 0, 0, 0, 1, 3, 4, 3, 3, 3, 5, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0,
		 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0,
		 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0};

BitmapImage bomb_0 = BitmapImage((const uint8_t*)bomb_0_bitmap, 11, 11, &bomb_colorLUT);

const uint8_t bomb_1_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 6, 2, 0, 0, 0, 1, 1,
		 0, 0, 0, 0, 2, 0, 0, 1, 1, 3, 3, 1, 1, 0, 0, 0, 0, 1, 3, 4, 4, 5, 3, 5,
		 1, 0, 0, 0, 1, 3, 4, 3, 3, 3, 5, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0,
		 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0,
		 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0};

BitmapImage bomb_1 = BitmapImage((const uint8_t*)bomb_1_bitmap, 11, 11, &bomb_colorLUT);

const uint8_t bomb_2_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 1, 0, 0, 1, 7, 0, 0, 0, 0, 1, 1, 0, 0, 0, 7, 2, 7, 0, 0, 0, 1, 1,
		 0, 0, 0, 0, 7, 0, 0, 1, 1, 3, 3, 1, 1, 0, 0, 0, 0, 1, 3, 4, 8, 9, 3, 9,
		 1, 0, 0, 0, 1, 3, 4, 3, 3, 3, 9, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0,
		 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0,
		 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0};

BitmapImage bomb_2 = BitmapImage((const uint8_t*)bomb_2_bitmap, 11, 11, &bomb_colorLUT);

const uint8_t bomb_3_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 1, 0, 0, 1, 7, 0, 0, 0, 0, 1, 1, 0, 0, 0, 7, 10, 7, 0, 0, 0, 1, 1,
		 0, 0, 0, 0, 7, 0, 0, 1, 1, 3, 3, 1, 1, 0, 0, 0, 0, 1, 3, 4, 11, 12, 13,
		 12, 1, 0, 0, 0, 1, 3, 4, 3, 3, 13, 12, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 13,
		 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 1, 3, 3, 3, 3, 3, 3, 1, 0,
		 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0};

BitmapImage bomb_3 = BitmapImage((const uint8_t*)bomb_3_bitmap, 11, 11, &bomb_colorLUT);