#include <stdint.h>
#include "graphics/bitmapImage.hpp"
#include "graphics/colorLUT.hpp"
//This file is autogenerated and contains asset data to be stored in ROM.
//(c) Daniel Cooper and Artists 2021

const uint16_t charset_colorLUT_lut[] = { 0, 0};

ColorLUT charset_colorLUT = ColorLUT((uint16_t*)charset_colorLUT_lut);

const uint8_t charset_0_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_0 = BitmapImage((const uint8_t*)charset_0_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_1_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_1 = BitmapImage((const uint8_t*)charset_1_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_2_bitmap[] = { 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
		 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_2 = BitmapImage((const uint8_t*)charset_2_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_3_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
		 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_3 = BitmapImage((const uint8_t*)charset_3_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_4_bitmap[] = { 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
		 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_4 = BitmapImage((const uint8_t*)charset_4_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_5_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_5 = BitmapImage((const uint8_t*)charset_5_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_6_bitmap[] = { 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
		 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_6 = BitmapImage((const uint8_t*)charset_6_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_7_bitmap[] = { 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
		 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_7 = BitmapImage((const uint8_t*)charset_7_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_8_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_8 = BitmapImage((const uint8_t*)charset_8_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_9_bitmap[] = { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_9 = BitmapImage((const uint8_t*)charset_9_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_10_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
		 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_10 = BitmapImage((const uint8_t*)charset_10_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_11_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
		 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_11 = BitmapImage((const uint8_t*)charset_11_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_12_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_12 = BitmapImage((const uint8_t*)charset_12_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_13_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_13 = BitmapImage((const uint8_t*)charset_13_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_14_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_14 = BitmapImage((const uint8_t*)charset_14_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_15_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_15 = BitmapImage((const uint8_t*)charset_15_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_16_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_16 = BitmapImage((const uint8_t*)charset_16_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_17_bitmap[] = { 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_17 = BitmapImage((const uint8_t*)charset_17_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_18_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
		 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_18 = BitmapImage((const uint8_t*)charset_18_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_19_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
		 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_19 = BitmapImage((const uint8_t*)charset_19_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_20_bitmap[] = { 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
		 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_20 = BitmapImage((const uint8_t*)charset_20_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_21_bitmap[] = { 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
		 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_21 = BitmapImage((const uint8_t*)charset_21_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_22_bitmap[] = { 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_22 = BitmapImage((const uint8_t*)charset_22_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_23_bitmap[] = { 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_23 = BitmapImage((const uint8_t*)charset_23_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_24_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_24 = BitmapImage((const uint8_t*)charset_24_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_25_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_25 = BitmapImage((const uint8_t*)charset_25_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_26_bitmap[] = { 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
		 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_26 = BitmapImage((const uint8_t*)charset_26_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_27_bitmap[] = { 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
		 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
		 0, 0, 0};

BitmapImage charset_27 = BitmapImage((const uint8_t*)charset_27_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_28_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
		 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_28 = BitmapImage((const uint8_t*)charset_28_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_29_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
		 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_29 = BitmapImage((const uint8_t*)charset_29_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_30_bitmap[] = { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_30 = BitmapImage((const uint8_t*)charset_30_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_31_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
		 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_31 = BitmapImage((const uint8_t*)charset_31_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_32_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
		 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_32 = BitmapImage((const uint8_t*)charset_32_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_33_bitmap[] = { 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_33 = BitmapImage((const uint8_t*)charset_33_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_34_bitmap[] = { 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_34 = BitmapImage((const uint8_t*)charset_34_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_35_bitmap[] = { 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
		 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_35 = BitmapImage((const uint8_t*)charset_35_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_36_bitmap[] = { 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_36 = BitmapImage((const uint8_t*)charset_36_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_37_bitmap[] = { 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_37 = BitmapImage((const uint8_t*)charset_37_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_38_bitmap[] = { 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_38 = BitmapImage((const uint8_t*)charset_38_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_39_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_39 = BitmapImage((const uint8_t*)charset_39_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_40_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_40 = BitmapImage((const uint8_t*)charset_40_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_41_bitmap[] = { 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_41 = BitmapImage((const uint8_t*)charset_41_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_42_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
		 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_42 = BitmapImage((const uint8_t*)charset_42_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_43_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
		 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_43 = BitmapImage((const uint8_t*)charset_43_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_44_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_44 = BitmapImage((const uint8_t*)charset_44_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_45_bitmap[] = { 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
		 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_45 = BitmapImage((const uint8_t*)charset_45_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_46_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
		 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_46 = BitmapImage((const uint8_t*)charset_46_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_47_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_47 = BitmapImage((const uint8_t*)charset_47_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_48_bitmap[] = { 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_48 = BitmapImage((const uint8_t*)charset_48_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_49_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_49 = BitmapImage((const uint8_t*)charset_49_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_50_bitmap[] = { 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_50 = BitmapImage((const uint8_t*)charset_50_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_51_bitmap[] = { 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_51 = BitmapImage((const uint8_t*)charset_51_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_52_bitmap[] = { 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_52 = BitmapImage((const uint8_t*)charset_52_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_53_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_53 = BitmapImage((const uint8_t*)charset_53_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_54_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_54 = BitmapImage((const uint8_t*)charset_54_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_55_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
		 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_55 = BitmapImage((const uint8_t*)charset_55_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_56_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_56 = BitmapImage((const uint8_t*)charset_56_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_57_bitmap[] = { 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_57 = BitmapImage((const uint8_t*)charset_57_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_58_bitmap[] = { 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
		 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_58 = BitmapImage((const uint8_t*)charset_58_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_59_bitmap[] = { 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
		 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_59 = BitmapImage((const uint8_t*)charset_59_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_60_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_60 = BitmapImage((const uint8_t*)charset_60_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_61_bitmap[] = { 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
		 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_61 = BitmapImage((const uint8_t*)charset_61_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_62_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
		 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_62 = BitmapImage((const uint8_t*)charset_62_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_63_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 1, 1};

BitmapImage charset_63 = BitmapImage((const uint8_t*)charset_63_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_64_bitmap[] = { 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
		 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_64 = BitmapImage((const uint8_t*)charset_64_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_65_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_65 = BitmapImage((const uint8_t*)charset_65_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_66_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_66 = BitmapImage((const uint8_t*)charset_66_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_67_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_67 = BitmapImage((const uint8_t*)charset_67_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_68_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
		 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_68 = BitmapImage((const uint8_t*)charset_68_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_69_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_69 = BitmapImage((const uint8_t*)charset_69_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_70_bitmap[] = { 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
		 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_70 = BitmapImage((const uint8_t*)charset_70_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_71_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
		 1, 1, 0};

BitmapImage charset_71 = BitmapImage((const uint8_t*)charset_71_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_72_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_72 = BitmapImage((const uint8_t*)charset_72_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_73_bitmap[] = { 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_73 = BitmapImage((const uint8_t*)charset_73_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_74_bitmap[] = { 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
		 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
		 1, 0, 0};

BitmapImage charset_74 = BitmapImage((const uint8_t*)charset_74_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_75_bitmap[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_75 = BitmapImage((const uint8_t*)charset_75_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_76_bitmap[] = { 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_76 = BitmapImage((const uint8_t*)charset_76_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_77_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
		 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_77 = BitmapImage((const uint8_t*)charset_77_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_78_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_78 = BitmapImage((const uint8_t*)charset_78_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_79_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_79 = BitmapImage((const uint8_t*)charset_79_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_80_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
		 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
		 0, 0, 0};

BitmapImage charset_80 = BitmapImage((const uint8_t*)charset_80_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_81_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
		 0, 0, 1};

BitmapImage charset_81 = BitmapImage((const uint8_t*)charset_81_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_82_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
		 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_82 = BitmapImage((const uint8_t*)charset_82_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_83_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
		 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_83 = BitmapImage((const uint8_t*)charset_83_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_84_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
		 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_84 = BitmapImage((const uint8_t*)charset_84_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_85_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_85 = BitmapImage((const uint8_t*)charset_85_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_86_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_86 = BitmapImage((const uint8_t*)charset_86_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_87_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_87 = BitmapImage((const uint8_t*)charset_87_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_88_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_88 = BitmapImage((const uint8_t*)charset_88_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_89_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
		 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
		 1, 1, 0};

BitmapImage charset_89 = BitmapImage((const uint8_t*)charset_89_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_90_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
		 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_90 = BitmapImage((const uint8_t*)charset_90_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_91_bitmap[] = { 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
		 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
		 0, 0, 0};

BitmapImage charset_91 = BitmapImage((const uint8_t*)charset_91_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_92_bitmap[] = { 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
		 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
		 1, 0, 0};

BitmapImage charset_92 = BitmapImage((const uint8_t*)charset_92_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_93_bitmap[] = { 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
		 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_93 = BitmapImage((const uint8_t*)charset_93_bitmap, 5, 8, &charset_colorLUT);

const uint8_t charset_94_bitmap[] = { 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
		 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0};

BitmapImage charset_94 = BitmapImage((const uint8_t*)charset_94_bitmap, 5, 8, &charset_colorLUT);

BitmapImage* characters[] = {&charset_0, &charset_1, &charset_2, &charset_3, &charset_4, &charset_5,
                             &charset_6, &charset_7, &charset_8, &charset_9, &charset_10, &charset_11,
                             &charset_12, &charset_13, &charset_14, &charset_15, &charset_16, &charset_17,
                             &charset_18, &charset_19, &charset_20, &charset_21, &charset_22, &charset_23,
                             &charset_24, &charset_25, &charset_26, &charset_27, &charset_28, &charset_29,
                             &charset_30, &charset_31, &charset_32, &charset_33, &charset_34, &charset_35,
                             &charset_36, &charset_37, &charset_38, &charset_39, &charset_40, &charset_41,
                             &charset_42, &charset_43, &charset_44, &charset_45, &charset_46, &charset_47,
                             &charset_48, &charset_49, &charset_50, &charset_51, &charset_52, &charset_53,
                             &charset_54, &charset_55, &charset_56, &charset_57, &charset_58, &charset_59,
                             &charset_60, &charset_61, &charset_62, &charset_63, &charset_64, &charset_65,
                             &charset_66, &charset_67, &charset_68, &charset_69, &charset_70, &charset_71,
                             &charset_72, &charset_73, &charset_74, &charset_75, &charset_76, &charset_77,
                             &charset_78, &charset_79, &charset_80, &charset_81, &charset_82, &charset_83,
                             &charset_84, &charset_85, &charset_86, &charset_87, &charset_88, &charset_89,
                             &charset_90, &charset_91, &charset_92, &charset_93, &charset_94};