#include <stdint.h>
#include "graphics/bitmapImage.hpp"
#include "graphics/colorLUT.hpp"
//This file is autogenerated and contains asset data to be stored in ROM.
//(c) Daniel Cooper and Artists 2021

const uint16_t knife_colorLUT_lut[] = { 0, 0, 23494};

ColorLUT knife_colorLUT = ColorLUT((uint16_t*)knife_colorLUT_lut);

const uint8_t knife_0_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
		 2, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2,
		 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_0 = BitmapImage((const uint8_t*)knife_0_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_1_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 2, 2, 2,
		 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_1 = BitmapImage((const uint8_t*)knife_1_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_2_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
		 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2,
		 2, 2};

BitmapImage knife_2 = BitmapImage((const uint8_t*)knife_2_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_3_bitmap[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
		 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0,
		 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0,
		 0, 0};

BitmapImage knife_3 = BitmapImage((const uint8_t*)knife_3_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_4_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 1, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 0,
		 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_4 = BitmapImage((const uint8_t*)knife_4_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_5_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
		 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_5 = BitmapImage((const uint8_t*)knife_5_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_6_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0,
		 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2,
		 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_6 = BitmapImage((const uint8_t*)knife_6_bitmap, 8, 8, &knife_colorLUT);

const uint8_t knife_7_bitmap[] = { 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 2, 2,
		 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0,
		 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		 0, 0};

BitmapImage knife_7 = BitmapImage((const uint8_t*)knife_7_bitmap, 8, 8, &knife_colorLUT);