#include <stdint.h>
#include "graphics/bitmapImage.hpp"
#include "graphics/colorLUT.hpp"
//This file is autogenerated and contains asset data to be stored in ROM.
//(c) Daniel Cooper and Artists 2021

const uint16_t knifeMarker_colorLUT_lut[] = { 0, 65535, 43482, 15591, 27082,
		 39638, 3019, 6342, 52939};

ColorLUT knifeMarker_colorLUT = ColorLUT((uint16_t*)knifeMarker_colorLUT_lut);

const uint8_t knifeMarker_0_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
		 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0};

BitmapImage knifeMarker_0 = BitmapImage((const uint8_t*)knifeMarker_0_bitmap, 5, 5, &knifeMarker_colorLUT);

const uint8_t knifeMarker_1_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3,
		 4, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0};

BitmapImage knifeMarker_1 = BitmapImage((const uint8_t*)knifeMarker_1_bitmap, 5, 5, &knifeMarker_colorLUT);

const uint8_t knifeMarker_2_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 5,
		 6, 5, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0};

BitmapImage knifeMarker_2 = BitmapImage((const uint8_t*)knifeMarker_2_bitmap, 5, 5, &knifeMarker_colorLUT);

const uint8_t knifeMarker_3_bitmap[] = { 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7,
		 8, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0};

BitmapImage knifeMarker_3 = BitmapImage((const uint8_t*)knifeMarker_3_bitmap, 5, 5, &knifeMarker_colorLUT);